/* Cosmos 3D application: dependency-free runtime with graceful API fallbacks. */
const NASA_API_KEY = 'DEMO_KEY';
const APOD_API = `https://api.nasa.gov/planetary/apod?api_key=${NASA_API_KEY}`;
const ISS_API = 'https://api.open-notify.org/iss-now.json';
const PEOPLE_API = 'https://api.open-notify.org/astros.json';
let heroRenderer, planetsRenderer, planetsScene, currentPlanet;

const planetsData = {
  mercury:{name:'Mercury',color:0x8c7853,size:.8,type:'Terrestrial',distance:'57.9M km',diameter:'4,879 km',moons:'0'}, venus:{name:'Venus',color:0xffc649,size:1,type:'Terrestrial',distance:'108.2M km',diameter:'12,104 km',moons:'0'}, earth:{name:'Earth',color:0x0ea5e9,size:1,type:'Terrestrial',distance:'149.6M km',diameter:'12,742 km',moons:'1'}, mars:{name:'Mars',color:0xdc2626,size:.9,type:'Terrestrial',distance:'227.9M km',diameter:'6,779 km',moons:'2'}, jupiter:{name:'Jupiter',color:0xd97706,size:2,type:'Gas Giant',distance:'778.5M km',diameter:'139,820 km',moons:'95'}, saturn:{name:'Saturn',color:0xfbbf24,size:1.8,type:'Gas Giant',distance:'1.4B km',diameter:'116,460 km',moons:'146'}, uranus:{name:'Uranus',color:0x06b6d4,size:1.3,type:'Ice Giant',distance:'2.9B km',diameter:'50,724 km',moons:'27'}, neptune:{name:'Neptune',color:0x3b82f6,size:1.3,type:'Ice Giant',distance:'4.5B km',diameter:'49,244 km',moons:'14'}
};
const missions = [
  ['🌕','Chandrayaan-3','ISRO','Success','India’s third lunar mission achieved a historic soft landing near the Moon’s south pole.','Moon - South Pole','2023'],
  ['🔭','James Webb Telescope','NASA','Active','Revolutionary space telescope observing the universe in infrared wavelengths.','L2 Lagrange Point','2021'],
  ['☀️','Aditya-L1','ISRO','Active','India’s first solar mission studying the Sun’s corona and solar winds.','L1 Lagrange Point','2023'],
  ['🔴','Mars Perseverance','NASA','Active','Advanced rover searching for signs of ancient microbial life on Mars.','Jezero Crater, Mars','2020'],
  ['🚀','Gaganyaan','ISRO','Upcoming','India’s first crewed spaceflight mission to low Earth orbit.','LEO','2025+'],
  ['🌙','Artemis Program','NASA','In Progress','NASA’s program to return humans to the Moon and establish a sustainable presence.','Moon','Ongoing']
];
function el(id){return document.getElementById(id)}
function initLoading(){const bar=el('loading-bar'), percent=el('loading-percent'), text=el('loading-text'), screen=el('loading-screen'); let p=0; const timer=setInterval(()=>{p=Math.min(100,p+20); bar.style.width=`${p}%`; percent.textContent=`${p}%`; text.textContent=['Starting starfield...','Preparing 3D engine...','Loading mission data...','Connecting to live telemetry...','Ready for launch!'][p/20-1]; if(p===100){clearInterval(timer);setTimeout(()=>screen.classList.add('hidden'),350)}},120)}
function initStarfield(){const canvas=el('starfield'),ctx=canvas.getContext('2d'),stars=[]; const resize=()=>{canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width='100%';canvas.style.height='100%';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}; resize(); addEventListener('resize',resize); for(let i=0;i<450;i++)stars.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.8+.2,s:Math.random()*.35+.05,o:Math.random()}); (function draw(){ctx.fillStyle='rgba(10,14,39,.25)';ctx.fillRect(0,0,innerWidth,innerHeight);stars.forEach(s=>{ctx.fillStyle=`rgba(255,255,255,${s.o})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();s.y+=s.s;if(s.y>innerHeight){s.y=0;s.x=Math.random()*innerWidth}});requestAnimationFrame(draw)})()}
function initHero3D(){const c=el('hero-3d'); if(!c||typeof THREE==='undefined')return; const s=new THREE.Scene(),cam=new THREE.PerspectiveCamera(60,Math.max(c.clientWidth,1)/Math.max(c.clientHeight,1),.1,100); heroRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true}); heroRenderer.setPixelRatio(Math.min(devicePixelRatio,2)); heroRenderer.setSize(c.clientWidth,c.clientHeight); c.appendChild(heroRenderer.domElement); cam.position.z=5; const earth=new THREE.Mesh(new THREE.SphereGeometry(2,48,48),new THREE.MeshPhongMaterial({color:0x0ea5e9,emissive:0x003344,shininess:50})); s.add(earth); const stars=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xffffff,size:.06})); const v=[];for(let i=0;i<1200;i++)v.push((Math.random()-.5)*50,(Math.random()-.5)*50,(Math.random()-.5)*50);stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(v,3));s.add(stars);s.add(new THREE.AmbientLight(0xffffff,.5));const light=new THREE.PointLight(0x00d4ff,2,100);light.position.set(5,5,5);s.add(light); const resize=()=>{cam.aspect=Math.max(c.clientWidth,1)/Math.max(c.clientHeight,1);cam.updateProjectionMatrix();heroRenderer.setSize(c.clientWidth,c.clientHeight)};addEventListener('resize',resize);(function loop(){earth.rotation.y+=.002;stars.rotation.y+=.0004;heroRenderer.render(s,cam);requestAnimationFrame(loop)})()}
function initPlanets3D(){const canvas=el('planets-canvas');if(!canvas||typeof THREE==='undefined')return;planetsScene=new THREE.Scene();const cam=new THREE.PerspectiveCamera(50,1,.1,100);cam.position.z=5;planetsRenderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});const resize=()=>{const w=canvas.clientWidth||600,h=canvas.clientHeight||400;planetsRenderer.setSize(w,h,false);cam.aspect=w/h;cam.updateProjectionMatrix()};resize();addEventListener('resize',resize);planetsScene.add(new THREE.AmbientLight(0xffffff,.7));const light=new THREE.PointLight(0xffffff,2);light.position.set(5,3,5);planetsScene.add(light);switchPlanet('earth');document.querySelectorAll('.planet-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.planet-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');switchPlanet(b.dataset.planet)}));(function loop(){if(currentPlanet)currentPlanet.rotation.y+=.006;planetsRenderer.render(planetsScene,cam);requestAnimationFrame(loop)})()}
function switchPlanet(name){if(!planetsScene||!planetsData[name])return;if(currentPlanet){currentPlanet.geometry.dispose();currentPlanet.material.dispose();planetsScene.remove(currentPlanet)}const d=planetsData[name];currentPlanet=new THREE.Mesh(new THREE.SphereGeometry(d.size,48,48),new THREE.MeshPhongMaterial({color:d.color,emissive:d.color,emissiveIntensity:.12}));planetsScene.add(currentPlanet);const info=el('planet-info');if(info){info.querySelector('.planet-name').textContent=d.name;info.querySelectorAll('.detail').forEach((x,i)=>x.innerHTML=`<span>${['Type','Distance','Diameter','Moons'][i]}:</span> ${[d.type,d.distance,d.diameter,d.moons][i]}`)}}
function loadMissions(){el('missions-grid').innerHTML=missions.map(m=>`<article class="mission-card"><div style="font-size:3rem">${m[0]}</div><h3>${m[1]}</h3><p>${m[4]}</p><div class="mission-meta"><span>📍 ${m[5]}</span><span>🚀 ${m[6]}</span><span>⚡ ${m[3]}</span></div></article>`).join('')}
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function updateISS(){try{const d=await json(ISS_API),lat=Number(d.iss_position.latitude),lon=Number(d.iss_position.longitude);el('iss-lat').textContent=`${lat.toFixed(2)}°`;el('iss-lon').textContent=`${lon.toFixed(2)}°`;el('live-status').textContent='Live data connected • ISS position updated'}catch(e){el('live-status').textContent='Live telemetry unavailable • Showing last known values'}}
async function updatePeople(){try{const d=await json(PEOPLE_API);el('people-in-space').textContent=d.number;el('astronaut-list').innerHTML=d.people.slice(0,8).map(p=>`<div class="highlight-item">👨‍🚀 ${p.name} <small>(${p.craft})</small></div>`).join('')}catch(e){el('astronaut-list').innerHTML='<div class="highlight-item">Crew data temporarily unavailable.</div>'}}
async function loadAPOD(){try{const d=await json(APOD_API);el('apod-title').textContent=d.title;el('apod-explanation').textContent=(d.explanation||'').slice(0,320);el('apod-date').textContent=d.date||'';if(d.media_type==='image'&&d.url){const img=el('apod-image');img.src=d.url;img.style.display='block';el('apod-loader').style.display='none'}}catch(e){el('apod-loader').innerHTML='<div class="highlight-item">NASA image temporarily unavailable.</div>'}}
function initNavigation(){const menu=document.querySelector('.nav-menu'),toggle=el('nav-toggle');toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('active');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-item').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('active')));addEventListener('scroll',()=>el('navbar').classList.toggle('scrolled',scrollY>60),{passive:true})}
function updateTime(){el('last-update').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',timeZoneName:'short'})}
function init(){initLoading();initStarfield();initHero3D();initPlanets3D();loadMissions();initNavigation();updatePeople();updateISS();loadAPOD();updateTime();setInterval(updateISS,60000);setInterval(updatePeople,60000);setInterval(updateTime,1000)}
addEventListener('DOMContentLoaded',init);
